# Generated by Django 4.2.7 on 2025-08-02 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('severity_level', models.IntegerField(choices=[(1, 'Mild'), (2, 'Moderate'), (3, 'Severe'), (4, 'Critical')], default=1)),
                ('category', models.CharField(choices=[('infectious', 'Infectious Disease'), ('chronic', 'Chronic Disease'), ('genetic', 'Genetic Disorder'), ('autoimmune', 'Autoimmune Disease'), ('cancer', 'Cancer'), ('mental', 'Mental Health'), ('cardiovascular', 'Cardiovascular'), ('respiratory', 'Respiratory'), ('gastrointestinal', 'Gastrointestinal'), ('neurological', 'Neurological'), ('other', 'Other')], default='other', max_length=50)),
                ('treatment', models.TextField(blank=True, null=True)),
                ('prevention', models.TextField(blank=True, null=True)),
                ('risk_factors', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DiseasePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(default=0.0)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictionDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.FloatField(default=0.0)),
                ('rank', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-probability'],
            },
        ),
        migrations.CreateModel(
            name='PredictionSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.IntegerField(choices=[(1, 'Mild'), (2, 'Moderate'), (3, 'Severe'), (4, 'Critical')], default=1)),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diseases.diseaseprediction')),
            ],
        ),
    ]
