# Generated by Django 4.2.7 on 2025-08-02 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('symptoms', '0001_initial'),
        ('diseases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionsymptom',
            name='symptom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptoms.symptom'),
        ),
        migrations.AddField(
            model_name='predictiondisease',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diseases.disease'),
        ),
        migrations.AddField(
            model_name='predictiondisease',
            name='prediction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diseases.diseaseprediction'),
        ),
        migrations.AddField(
            model_name='diseaseprediction',
            name='predicted_diseases',
            field=models.ManyToManyField(through='diseases.PredictionDisease', to='diseases.disease'),
        ),
        migrations.AddField(
            model_name='diseaseprediction',
            name='symptoms',
            field=models.ManyToManyField(through='diseases.PredictionSymptom', to='symptoms.symptom'),
        ),
    ]
