# Generated by Django 4.2.7 on 2025-08-02 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('symptoms', '0001_initial'),
        ('diseases', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diseaseprediction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_predictions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disease',
            name='symptoms',
            field=models.ManyToManyField(related_name='diseases', to='symptoms.symptom'),
        ),
        migrations.AlterUniqueTogether(
            name='predictionsymptom',
            unique_together={('prediction', 'symptom')},
        ),
        migrations.AlterUniqueTogether(
            name='predictiondisease',
            unique_together={('prediction', 'disease')},
        ),
    ]
