# Generated by Django 4.2.7 on 2025-08-02 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('severity_level', models.IntegerField(choices=[(1, 'Mild'), (2, 'Moderate'), (3, 'Severe'), (4, 'Critical')], default=1)),
                ('category', models.CharField(choices=[('respiratory', 'Respiratory'), ('cardiovascular', 'Cardiovascular'), ('neurological', 'Neurological'), ('gastrointestinal', 'Gastrointestinal'), ('musculoskeletal', 'Musculoskeletal'), ('skin', 'Skin'), ('eye', 'Eye'), ('ear', 'Ear'), ('mental', 'Mental Health'), ('general', 'General')], default='general', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SymptomCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SymptomCheckDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.IntegerField(choices=[(1, 'Mild'), (2, 'Moderate'), (3, 'Severe'), (4, 'Critical')], default=1)),
                ('duration_days', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptoms.symptom')),
                ('symptom_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptoms.symptomcheck')),
            ],
        ),
        migrations.AddField(
            model_name='symptomcheck',
            name='symptoms',
            field=models.ManyToManyField(through='symptoms.SymptomCheckDetail', to='symptoms.symptom'),
        ),
    ]
