# Generated by Django 5.2.1 on 2025-05-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipes_name', models.CharField(max_length=200)),
                ('recipes_dec', models.CharField(max_length=500)),
                ('recipes_rating', models.IntegerField(default=0)),
            ],
        ),
    ]
