# Generated by Django 5.2.1 on 2025-05-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='recipes_image',
            field=models.ImageField(default=2, upload_to='RecipesIMG'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipes',
            name='recipes_inst',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
