# Generated by Django 5.2.1 on 2025-05-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipes_recipes_image_recipes_recipes_inst'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='recipes_cooktime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipes',
            name='recipes_ingri',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
