# Generated by Django 5.2.1 on 2025-05-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipes_recipes_cooktime_recipes_recipes_ingri'),
    ]

    operations = [
        migrations.CreateModel(
            name='requestrecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_Name', models.CharField(max_length=50)),
                ('recipe_shoetdesc', models.CharField(max_length=300)),
                ('recipe_ingre', models.CharField(max_length=500)),
                ('recipe_instr', models.CharField(max_length=500)),
                ('recipes_img', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
