# Generated by Django 4.2.7 on 2025-08-02 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('symptoms', '0001_initial'),
        ('diseases', '0001_initial'),
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinerecommendation',
            name='symptom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_recommendations', to='symptoms.symptom'),
        ),
        migrations.AddField(
            model_name='medicinecategory',
            name='medicines',
            field=models.ManyToManyField(blank=True, related_name='categories', to='medicines.medicine'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='treats_diseases',
            field=models.ManyToManyField(blank=True, related_name='medicines', to='diseases.disease'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='treats_symptoms',
            field=models.ManyToManyField(blank=True, related_name='medicines', to='symptoms.symptom'),
        ),
    ]
